--------------------------------------------------------
--  File created - Monday-June-01-2020   
--------------------------------------------------------
REM INSERTING into RESTSCOTT3.CONFIGURATION
SET DEFINE OFF;
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (464,'Gauche','Extra',685,458);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (465,'Droite','Peu',685,256);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (168,'Gauche','Moyen',415,235);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (169,'Droite','Peu',415,100);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (718,'Gauche','Extra',454,598);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (719,'Droite','Extra',454,654);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (157,'Gauche','Peu',964,357);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (158,'Droite','Moyen',964,119);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (518,'Gauche','Moyen',168,458);
Insert into RESTSCOTT3.CONFIGURATION (CONFIG_ID,EMPLACEMENT,"QUANTITÉ",PIZZA_PIZZA_ID,GARNITURE_GARNITURE_ID) values (519,'Droite','Extra',168,623);
